### ISSUE TITLE
training time

### ISSUE THREAD

**Issue by MacieJayDaaaaa** [YuYue525/MobileSAM-pytorch#1]
Hello, may I ask which gpu you use for training? What is the overall time spent on training? thank you!

**Comment by YuYue525** [comment]
As I remenbered, when I use 1 V100 16G GPU (batch size = 1 * 8) and 1% SA-1B dataset (sa_000000 to sa_000009) as the training set, the training time is around 1 day. We also tried 4 V100 16G GPUs (batch size = 4 * 8) and 8% SA-1B dataset as the training set, the training time is around 2 days. Note: we need to run preprocess.py first to save the image features output from SAM image encoder, because this not only saves the GPU memory during training but also saves the training time (no need to go through SAM image encoder over and over again). Hope it helps you.

**Comment by MacieJayDaaaaa** [comment]
thank you
