### ISSUE TITLE
MobileSAM w/, w/o ONNX export inference time

### ISSUE THREAD

**Issue by JisuHann** [YuYue525/MobileSAM-pytorch#3]
Hi, Thanks for your splendid work.

I am curious on the inference time if we use this model.
Have you checked the inference time of [MobileSAM with ONNX export] or [MobileSAM with ONNX export]?

Thank you

**Comment by YuYue525** [comment]
I believe the inference time should be close to MobileSAM because of the same architecture. To be honest, I didn't check the inference time of [MobileSAM with ONNX export] or [MobileSAM with ONNX export], but for the model weights loaded, the inference time of MobileSAM encoder is around 0.0013s/it (the SAM image encoder is around 0.43s/it) on a simgle RTX 3090 GPU.

**Comment by JisuHann** [comment]
Thanks a lot!
